# Generated by Django 3.0.5 on 2021-05-20 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('completed', models.BooleanField(default=False)),
                ('repo', models.CharField(default='', max_length=120)),
                ('assigned_merge_user', models.CharField(default='', max_length=120)),
                ('deadline', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MergeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_username', models.CharField(blank=True, max_length=500, unique=True)),
                ('merge_password', models.CharField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
