# Generated by Django 3.0.5 on 2021-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merge', '0003_auto_20210501_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='assigned_merge_user',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='repo',
            field=models.CharField(default='', max_length=120),
        ),
    ]
