# Generated by Django 3.0.5 on 2021-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merge', '0004_auto_20210502_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergeprofile',
            name='merge_username',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
